### ISSUE TITLE
Downloading the relevant jar file?

### ISSUE THREAD

**Issue by bbrancar** [commoncrawl/cc-index-table#27]
Hi,

I have successfully downloaded a csv via Amazon Athena and would like to perform bulk download of the listed WARC files. After cloning the Github and setting my $SPARK_HOME to my download of pyspark in my virtual environment, I have run the code: 

`> $SPARK_HOME/bin/spark-submit --class org.commoncrawl.spark.examples.CCIndexWarcExport $APPJAR \
   --csv xyx
   ...`

This returned the error: `Failed to find Spark jars directory (xyz)`. Do you have any suggestions on how I can resolve this issue?

Thank you

**Comment by sebastian-nagel** [comment]
The Spark jars directory is `$SPARK_HOME/jars/`.
- first, I would make sure that the directory exists and actually contains a long list of *.jar files.
- note that downloading PySpark may not be sufficient: the cc-index-table project is based on Java. Please have a look at the [Spark documentation](https://spark.apache.org/docs/latest/)
- in case, you cannot resolve the problem, please share some more context (operating system, installed Java version, etc.)

**Comment by bbrancar** [comment]
This was helpful, I had failed to correctly download Spark. Thank you

**Comment by sebastian-nagel** [comment]
Thanks for the feed. I'll add a link to the Spark installation instructions in the README. Hope it helps future users.
