### ISSUE TITLE
WARC files unreadabe 

### ISSUE THREAD

**Issue by AmrSheta22** [commoncrawl/cc-index-table#31]
`ArchiveLoadFailed: Unknown archive format, first line: ['\\\x03$YgfÍZèÞç\x9cïËè\x1f1&Y\x995\x97÷\x9dç}\x9eç\x0bÝRÝ"Ñ\x0bz\x01\x1f¿\x15\x10\xa0Gñ\x0ey_£³!w©³6\x1aï\'\x81\x8dFÿ-\x84\x05`
I cannot read the file and I get an error like this.

**Comment by sebastian-nagel** [comment]
Hi @AmrSheta22, could you add the code you are executing, a short description what it should do, the complete path to the WARC file which is read and also the full (Java) stack trace.

**Comment by AmrSheta22** [comment]
Hi, turns out the WARC file I was reading is corrupted, sorry for the hustle.

**Comment by sebastian-nagel** [comment]
Thanks for the update, @AmrSheta22 !
